spring:
  datasource:
    url: jdbc:mysql://localhost:3306/tw_mall?characterEncoding=UTF-8&useSSL=false
    username: root
    password: t0iiz
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create